### ISSUE TITLE
"UnicodeEncodeError" exception: non-ASCII track name

### ISSUE THREAD

**Issue by raitonoberu** [alexmercerind/harmonoid-service#2]
The exception occurred when trying to download a track with Cyrillic in the title.

<details>

```
INFO:harmonoidservice.youtube:[server] Sending audio binary for track ID: 7nzMU6ive8Zpv6Puqid46W
INFO:werkzeug:127.0.0.1 - - [25/Aug/2020 02:04:46] "GET /trackdownload?track_id=7nzMU6ive8Zpv6Puqid46W HTTP/1.1" 200 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\Disith\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Disith\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 295, in execute
    write(data)
  File "C:\Users\Disith\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 258, in write
    self.send_header(key, value)
  File "C:\Users\Disith\AppData\Local\Programs\Python\Python38-32\Lib\http\server.py", line 516, in send_header
    ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 12-16: ordinal not in range(256)
```

</details>

I googled and found out that [HTTP header cant contain non-ASCII characters](https://github.com/benoitc/gunicorn/issues/2319).

These lines send the header with the downloaded file:
https://github.com/alexmercerind/harmonoid-service/blob/10fea370caac29aefe9cb65b814a0c0ac4dfe96e/harmonoidservice/youtube.py#L100-L101

Well, we may use `urllib.parse.quote(text)` to url-encode the value and then decode it in the frontend. Or we may not use headers at all.

@alexmercerind, what do you think about it?

**Comment by alexmercerind** [comment]
😅 I added those un-necessary headers in a relatively new commit... alexmercerind@2db664c4ba5bda29099b6004f3608a2b23fbc438

**I just added them for the README /trackdownload example. I didn't think that it can cause problem in future.**

The frontend flutter app infact DOES NOT USE them at all. It takes the required metadata from the trackInfo used at the time of rendering itself. So, I'm removing these lines

https://github.com/alexmercerind/harmonoid-service/blob/10fea370caac29aefe9cb65b814a0c0ac4dfe96e/harmonoidservice/youtube.py#L100-L101
https://github.com/alexmercerind/harmonoid-service/blob/10fea370caac29aefe9cb65b814a0c0ac4dfe96e/harmonoidservice/youtube.py#L134-L135

**Comment by alexmercerind** [comment]
I'm really sorry for my stupidity...

alexmercerind@f6a142495cf9a67acb82f623724a1f67633e9347

**Comment by alexmercerind** [comment]
Apart from above (bit off-topic)...
I made a commit here:
alexmercerind@ee4b83f47249ebef0de9cd290927a793624ed6b8

It fixes sometimes occurring incorrect downloads, when track has different artists than album artists.
I noticed this problem when I was fixing the problem that was causing wrong artist name in status bar (which you told).
